// apps/examples-angular/src/app/list-with-filters/list-with-filters.component.ts
import { AsyncPipe, JsonPipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  Injectable,
  signal,
  Signal,
  ViewChild
}                              from '@angular/core';
import {
  toObservable,
  toSignal
}                              from '@angular/core/rxjs-interop';
import {
  FormControl,
  FormGroup,
  FormsModule,
  ReactiveFormsModule
}                              from '@angular/forms';
import {
  MatButtonModule
}                              from '@angular/material/button';
import {
  MatCardModule
}                              from '@angular/material/card';
import {
  MatIconModule
}                              from '@angular/material/icon';
import {
  MatInputModule
}                              from '@angular/material/input';
import {
  MatPaginator,
  MatPaginatorIntl,
  PageEvent
}                              from '@angular/material/paginator';
import {
  MatProgressBarModule
}                              from '@angular/material/progress-bar';
import {
  MatSelectModule
}                              from '@angular/material/select';
import {
  MatSort,
  MatSortModule,
  Sort
}                              from '@angular/material/sort';
import {
  MatTableModule
}                              from '@angular/material/table';
import {
  Etf
}                              from '@org/common-lib';
import {
  debounceTime,
  map,
  merge,
  Observable,
  of,
  retry,
  startWith,
  Subject,
  switchMap,
  tap
}                              from 'rxjs';

import { EtfService } from './etf.service';


@Injectable()
class CustomMatPaginatorIntl extends MatPaginatorIntl {
  override itemsPerPageLabel = 'Wierszy na stronę';
  override nextPageLabel = 'Przejdź do następnej strony';
  override previousPageLabel = 'Przejdź do poprzedniej strony';
  override firstPageLabel = 'Przejdź do pierwszej strony';
  override lastPageLabel = 'Przejdź do ostatniej strony';
  
  override getRangeLabel = (page: number, pageSize: number, length: number) => {
    if (length === 0 || pageSize === 0) {
      return `0 z ${ length }`;
    }
    const startIndex = page * pageSize;
    // If the start index exceeds the list length, do not try and fix the end index to the end.
    const endIndex = startIndex < length ?
      Math.min(startIndex + pageSize, length) :
      startIndex + pageSize;
    return `${ startIndex + 1 } - ${ endIndex } z ${ length }`;
  };
}

const DEBOUNCE_TIME = 200;

interface Currency {
  code: string;
  name: string;
}

@Component({
  standalone: true,
  selector: 'app-list-with-filters',
  templateUrl: './list-with-filters.component.html',
  styleUrls: [ './list-with-filters.component.scss' ],
  providers: [ { provide: MatPaginatorIntl, useClass: CustomMatPaginatorIntl } ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    JsonPipe,
    AsyncPipe,
    FormsModule,
    ReactiveFormsModule,
    MatTableModule,
    MatProgressBarModule,
    MatInputModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatSortModule,
    MatButtonModule,
    MatPaginator
  ]
})
export class ListWithFiltersComponent {
  private readonly etfService = inject(EtfService);
  
  @ViewChild(MatSort, { static: true })
  private readonly matSort!: MatSort;
  
  protected readonly displayedColumns = [ 'name', 'price', 'currency' ];
  protected readonly currencies: Currency[] = [
    { code: 'USD', name: 'Dolar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'GBP', name: 'Funt' },
    { code: 'CHF', name: 'Frank' },
    { code: 'PLN', name: 'Złoty' }
  ];
  protected readonly pageSizes = [ 5, 10, 20, 50, 100 ];
  
  protected readonly loading = signal(false);
  protected readonly error = signal(false);
  protected readonly page = signal(1);
  protected readonly pageSize = signal(this.pageSizes[0]);
  protected readonly allItems = signal<number>(0);
  protected readonly sort = signal<Sort | null>(null);
  
  protected readonly retry$ = new Subject<void>();
  
  protected readonly filters = new FormGroup({
    search: new FormControl<string>('', { nonNullable: true }),
    priceMin: new FormControl<number | null>(null),
    priceMax: new FormControl<number | null>(null),
    currency: new FormControl<string | null>(null)
  });
  
  private readonly reloadValues$: Observable<unknown> = merge(
    this.filters.valueChanges.pipe(tap(() => {
      if (this.page() !== 1) {
        console.log('Update', this.page());
        this.page.set(1);
      }
    })),
    toObservable(this.page),
    toObservable(this.pageSize),
    toObservable(this.sort)
  );
  
  protected readonly loadedItems: Signal<Etf[]> = toSignal(
    this.reloadValues$.pipe(
      startWith(null),
      debounceTime(DEBOUNCE_TIME),
      switchMap(() => this.loadInstruments())
    ),
    { initialValue: [] }
  );
  
  private loadInstruments(): Observable<Etf[]> {
    return of(null).pipe(
      tap(() => {
        this.loading.set(true);
      }),
      switchMap(() => this.etfService.getEtfList(this.page(), this.pageSize(), this.filters.value, this.sort()?.active, this.sort()?.direction)),
      map((response) => {
        this.allItems.set(response.itemsCount);
        
        this.loading.set(false);
        this.error.set(false);
        
        return response.items;
      }),
      retry({
        delay: () => {
          this.loading.set(false);
          this.error.set(true);
          
          return this.retry$;
        }
      })
    );
  }
  
  protected resetFilters(): void {
    this.filters.reset();
    this.matSort.sort({ id: '', start: 'asc', disableClear: false });
  }
  
  protected element(el: unknown): Etf {
    return el as Etf;
  }
  
  protected handlePageEvent(e: PageEvent) {
    this.pageSize.set(e.pageSize);
    this.page.set(e.pageIndex + 1);
  }
}

<mat-card class="filters">
  <form [formGroup]="filters">
    <mat-card-content class="filters-content">

      <mat-form-field appearance="outline">
        <mat-label>Szukaj</mat-label>
        <input matInput placeholder="Szukaj..." formControlName="search">
        <mat-icon matSuffix>search</mat-icon>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Cena minimalna</mat-label>
        <input
          type="number"
          matInput
          placeholder="Cena minimalna"
          formControlName="priceMin"
        >
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Cena maksymalna</mat-label>
        <input
          type="number"
          matInput
          placeholder="Cena maksymalna"
          formControlName="priceMax"
        >
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Waluta</mat-label>
        <mat-select formControlName="currency">
          @for (currency of currencies; track currency.code) {
            <mat-option [value]="currency.code">{{ currency.name }}</mat-option>
          }
        </mat-select>
      </mat-form-field>

      <button mat-button (click)="resetFilters()" class="reset-btn">Wyczyść i przeładuj</button>
    </mat-card-content>
  </form>
</mat-card>

<mat-card class="table-container">
  <table
    mat-table
    [dataSource]="loadedItems()"
    matSort
    (matSortChange)="sort.set($event)"
    class="instruments-list"
  >
    <ng-container matColumnDef="name">
      <th
        mat-header-cell
        mat-sort-header
        sortActionDescription="Sortuj po nazwie"
        *matHeaderCellDef
      >
        Nazwa
      </th>

      <td mat-cell *matCellDef="let el"> {{ element(el).name }}</td>
    </ng-container>

    <ng-container matColumnDef="currency">
      <th
        mat-header-cell
        mat-sort-header
        sortActionDescription="Sortuj po walucie"
        *matHeaderCellDef
      >
        Waluta
      </th>

      <td mat-cell *matCellDef="let el"> {{ element(el).currency }}</td>
    </ng-container>

    <ng-container matColumnDef="price">
      <th mat-header-cell mat-sort-header sortActionDescription="Sortuj po cenie" *matHeaderCellDef>
        Cena
      </th>

      <td mat-cell *matCellDef="let el"> {{ element(el).price }}</td>
    </ng-container>

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
  </table>

  @if (error()) {
    <div class="error">
      @if (!loadedItems().length) {
        <svg
          class="icon"
          aria-hidden="true"
          viewBox="0 0 24 24"
          data-testid="ErrorIcon"
          title="Error"
        >
          <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m1 15h-2v-2h2zm0-4h-2V7h2z"></path>
        </svg>
      }
      <p>Wystąpił niespodziewany błąd</p>
      <button mat-button (click)="retry$.next()">Spróbuj ponownie</button>
    </div>
  }

  <mat-progress-bar
    class="loader"
    [class.loading-hide]="!loading()"
    mode="indeterminate"
  ></mat-progress-bar>

  <mat-paginator
    (page)="handlePageEvent($event)"
    [pageIndex]="page() - 1"
    [length]="allItems()"
    [pageSize]="pageSize()"
    [pageSizeOptions]="pageSizes"
    [showFirstLastButtons]="true"
  ></mat-paginator>
</mat-card>

// apps/examples-react/src/app/list-with-filters/ListWithFilters.tsx
import SearchIcon                from '@mui/icons-material/Search';
import {
  Box,
  Button,
  Card,
  FormControl,
  InputAdornment,
  InputLabel,
  LinearProgress,
  MenuItem,
  Paper,
  Select,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
  TextField,
  Typography
}                                from '@mui/material';
import { SelectChangeEvent }     from '@mui/material/Select/SelectInput';
import { Etf }                   from '@org/common-lib';
import { ChangeEvent, useState } from 'react';

import styles                 from './list-with-filters.module.scss';
import { useDebouncedEffect } from './use-debunce-effect';

import { useEtfsService } from './use-etfs';


interface Currency {
  code: string;
  name: string;
}

const pageSizes = [ 5, 10, 20, 50, 100 ];

const currencies: Currency[] = [
  { code: 'USD', name: 'Dolar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'Funt' },
  { code: 'CHF', name: 'Frank' },
  { code: 'PLN', name: 'Złoty' }
];

const headCells = [
  {
    name: 'name',
    label: 'Nazwa'
  }, {
    name: 'price',
    label: 'Cena'
  }, {
    name: 'currency',
    label: 'Waluta'
  }
];

export function ListWithFilters() {
  const [ rows, setRows ] = useState<Etf[]>([]);
  const [ allItems, setAllItems ] = useState(0);
  const [ filters, setFilters ] = useState({
    search: '', priceMin: '',
    priceMax: '', currency: '',
  });
  const [ sortProperty, setSortProperty ] = useState<undefined | string>(undefined);
  const [ sortDirection, setSortDirection ] = useState<undefined | 'asc' | 'desc'>(undefined);
  const [ page, setPage ] = useState(0);
  const [ pageSize, setPageSize ] = useState(pageSizes[0]);
  const [ isLoading, setIsLoading ] = useState(false);
  const [ isError, setIsError ] = useState(false);
  const [ retry, setRetry ] = useState(0);
 
  
  const etfService = useEtfsService();
  
  function handleCurrencyChange(e: SelectChangeEvent<string>): void {
    setFilters( f => ({ ...f, currency: e.target?.value ?? '' }));
  }
  
  function handleChangePage(_: unknown, newPage: number) {
    setPage(newPage);
  }
  
  function handleChangeRowsPerPage(event: ChangeEvent<HTMLInputElement>) {
    setPageSize(parseInt(event.target.value, 10));
    setPage(0);
  }
  
  function handleClear(): void {
    setFilters({
      search: '',
      priceMin: '',
      priceMax: '',
      currency: '',
    });
    setSortProperty(undefined);
    setSortDirection(undefined);
  }
  
useDebouncedEffect(() => {
    console.log({ retry });
    setIsLoading(true);
    
    const sub = etfService
      .getEtfList(
        page + 1,
        pageSize,
        {
          ...filters,
          priceMin: parseFloat(filters.priceMin) || null,
          priceMax: parseFloat(filters.priceMax) || null,
        },
        sortProperty,
        sortDirection
      )
      .subscribe({
        next: page => {
          console.log({ page });
          
          setRows(page.items);
          setAllItems(page.itemsCount);
          setIsLoading(false);
          setIsError(false);
        },
        error: (e) => {
          console.log({ e });
          
          setIsLoading(false);
          setIsError(true);
        }
      });
    
    return () => { sub.unsubscribe(); };
  },
  [ etfService, page, pageSize, filters, sortProperty, sortDirection, retry ],
  200
);
  
  // Avoid a layout jump when reaching the last page with empty rows.
  const emptyRows = pageSize - rows.length;
  
  function toggleSort(property: string) {
    const isAsc = sortProperty === property && sortDirection === 'asc';
    
    setSortProperty(property);
    setSortDirection(isAsc ? 'desc' : 'asc');
  }
  
  function handleRetry() {
    setRetry(v => v + 1);
  }
  
  return (
    <Box sx={ { maxWidth: 1000, margin: 'auto' } }>
      <form>
        <Card
          sx={ {
            p: 2,
            mb: 2,
            display: 'flex',
            gap: 1,
            alignItems: 'center',
            '& > *': { flex: 1 }
          } }
        >
          <TextField
            label="Szukaj"
            variant="outlined"
            InputProps={ {
              endAdornment: (
                <InputAdornment position="end">
                  <SearchIcon />
                </InputAdornment>
              )
            } }
            value={ filters.search }
            onChange={ e => setFilters(f => ({ ...f, search: e.target.value })) }
          />
          
          <TextField
            label="Cena minimalna"
            variant="outlined"
            type="number"
            value={ filters.priceMin }
            onChange={ e => setFilters(f => ({ ...f, priceMin: e.target.value })) }
          />
          <TextField
            label="Cena maksymalna"
            variant="outlined"
            type="number"
            value={ filters.priceMax }
            onChange={ e => setFilters(f => ({ ...f, priceMax: e.target.value })) }
          />
          
          <FormControl>
            <InputLabel>Waluta</InputLabel>
            
            <Select
              value={ filters.currency || '' }
              label="Waluta"
              onChange={ handleCurrencyChange }
              sx={ { minWidth: 120 } }
            >
              { currencies.map(currency => (
                <MenuItem
                  key={ currency.code }
                  value={ currency.code }
                >{ currency.name }</MenuItem>)
              ) }
            </Select>
          </FormControl>
          
          <Button onClick={ handleClear }>Wyczyść i przeładuj</Button>
        </Card>
      </form>
      
      <Paper sx={ { width: '100%', mb: 2 } }>
        <TableContainer>
          <Table sx={ { minWidth: 750 } }>
            <TableHead>
              <TableRow>
                { headCells.map((headCell) => (
                  <TableCell
                    key={ headCell.name }
                    sortDirection={ sortProperty === headCell.name ? sortDirection : false }
                  >
                    <TableSortLabel
                      active={ sortProperty === headCell.name }
                      direction={ sortProperty === headCell.name && sortDirection === 'desc' ? 'desc' : 'asc' }
                      onClick={ () => toggleSort(headCell.name) }
                    >
                      { headCell.label }
                    </TableSortLabel>
                  </TableCell>
                )) }
              </TableRow>
            </TableHead>
            
            <TableBody>
              { rows.map((row) => (
                <TableRow hover role="checkbox" key={ row.name }>
                  <TableCell>{ row.name }</TableCell>
                  <TableCell>{ row.price }</TableCell>
                  <TableCell>{ row.currency }</TableCell>
                </TableRow>
              )) }
              { (emptyRows > 0 && !isError) && (
                <TableRow style={ { height: 53 * emptyRows } }>
                  <TableCell colSpan={ 3 } />
                </TableRow>
              ) }
            </TableBody>
          </Table>
        </TableContainer>
        
        { isError && (
          <div className={ styles.error }>
            {
              !rows.length && (
                <svg
                  className={ styles.icon }
                  aria-hidden="true"
                  viewBox="0 0 24 24"
                  data-testid="ErrorIcon"
                >
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m1 15h-2v-2h2zm0-4h-2V7h2z"></path>
                </svg>
              )
            }
            <Typography>Wystąpił niespodziewany błąd</Typography>
            <Button onClick={ handleRetry }>Spróbuj ponownie</Button>
          </div>
        ) }
        
        { isLoading && <LinearProgress /> }
        
        <TablePagination
          className="paginator"
          component="div"
          sx={ { marginTop: isLoading ? '0' : '4px' } }
          rowsPerPageOptions={ pageSizes }
          count={ allItems }
          rowsPerPage={ pageSize }
          page={ page }
          showFirstButton
          showLastButton
          onPageChange={ handleChangePage }
          onRowsPerPageChange={ handleChangeRowsPerPage }
        />
      </Paper>
    </Box>
  );
}
