// apps/react-examples/src/app/App.tsx
import { Box, Container, Tab, Tabs } from '@mui/material'
import { useState }                  from 'react'

import { ListWithFilters } from '../list-with-filters'
import { SomePage }        from '../some-page'


export enum RoutesMap {
  ListWithFilters,
  SomePage,
}

export function App() {
  const [ path, setPath ] = useState(RoutesMap.ListWithFilters)
  
  function goTo(_: unknown, newPage: RoutesMap) {
    setPath(newPage)
  }
  
  return (
    <>
      <Tabs value={ path } onChange={ goTo } centered>
        <Tab label="Lista z filtrami" value={ RoutesMap.ListWithFilters } />
        <Tab label="Inny przykład" value={ RoutesMap.SomePage } />
      </Tabs>
      
      <Container maxWidth="xl">
        <Box sx={ { p: 3 } }>
          { path === RoutesMap.ListWithFilters && <ListWithFilters /> }
          { path === RoutesMap.SomePage && <SomePage /> }
        </Box>
      </Container>
    </>
  )
}

// apps/examples-angular/src/app/app.component.ts
import { Component }          from '@angular/core';
import { MatTabsModule }      from '@angular/material/tabs'

import { ListWithFiltersComponent } from './list-with-filters'

@Component({
  standalone: true,
  imports: [ MatTabsModule, ListWithFiltersComponent ],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {}

<mat-tab-group class="tabs">
  <mat-tab label="Lista z filtrami">
    <app-list-with-filters></app-list-with-filters>
  </mat-tab>

  <mat-tab label="Inny Przykład">
    Tab 2
  </mat-tab>
</mat-tab-group>
