// apps/examples-angular/src/app/app.component.ts
import { Component }          from '@angular/core';
import { MatTabsModule }      from '@angular/material/tabs'

import { ListWithFiltersComponent } from './list-with-filters'

@Component({
  standalone: true,
  imports: [ MatTabsModule, ListWithFiltersComponent ],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {}

<mat-tab-group class="tabs">
  <mat-tab label="Lista z filtrami">
    <app-list-with-filters></app-list-with-filters>
  </mat-tab>

  <mat-tab label="Inny Przykład">
    Tab 2
  </mat-tab>
</mat-tab-group>

// apps/examples-react/src/app/App.tsx
import { Box, Container, useTheme, createTheme, Tab, Tabs, ThemeProvider } from '@mui/material';
import {
  plPL
}                                                                          from '@mui/material/locale';
import { useMemo }                                               from 'react';

import { ListWithFilters } from './list-with-filters';

export function App() {
  const theme = useTheme();
  const themeWithLocale = useMemo(
    () => createTheme(theme, plPL),
    [ theme ]
  );
  
  return (
    <ThemeProvider theme={ themeWithLocale }>
      <Tabs sx={ { maxWidth: 1000, width: '100%', margin: 'auto' } }
      >
        <Tab
          sx={ { flex: 1, maxWidth: 1000 } }
          label="Lista z filtrami"
        />
        <Tab
          sx={ { flex: 1, maxWidth: 1000 } }
          label="Inny przykład"
        />
      </Tabs>
      
      <Container maxWidth="xl">
        <Box sx={ { p: 3 } }>
          <ListWithFilters />
          <p>Tab2</p>
        </Box>
      </Container>
    </ThemeProvider>
  );
}
